# Generated by Django 3.1 on 2020-10-06 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_voters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voters',
        ),
    ]
