# Generated by Django 3.1 on 2020-10-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_voted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voted',
            name='user_email',
            field=models.CharField(default='', max_length=128),
        ),
    ]
